// <auto-generated />
namespace Book_Shoppe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class UserDBv3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserDBv3));
        
        string IMigrationMetadata.Id
        {
            get { return "202002261226547_UserDB-v3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
