// <auto-generated />
namespace Book_Shoppe.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Database_v4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Database_v4));
        
        string IMigrationMetadata.Id
        {
            get { return "202003111052250_Database_v4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
